package controladores;

public enum TipoDesenho {
	RETA, CIRCULO, PONTO, CURVA_DO_DRAGAO, OPCAO_GERAL, RETA_ELASTICA, CIRCULO_ELASTICO, RETANGULO_ELASTICO, POLIGONO_ELASTICO,
	RETA_POLIGONAL, SELECIONAR_AREA_CLIPPING
}
